#pragma once

#include <cstdint>
#include <unordered_map>

namespace KeyMapping {

enum class GenericKey : uint8_t {
    ESC = 1,
    F1 = 2,   F2 = 3,   F3 = 4,   F4 = 5,
    F5 = 6,   F6 = 7,   F7 = 8,   F8 = 9,
    F9 = 10,  F10 = 11, F11 = 12, F12 = 13,
    GRAVE = 14,    // `
    NUM_1 = 15, NUM_2 = 16, NUM_3 = 17, NUM_4 = 18,
    NUM_5 = 19, NUM_6 = 20, NUM_7 = 21, NUM_8 = 22,
    NUM_9 = 23, NUM_0 = 24,
    MINUS = 25,    // -
    EQUALS = 26,   // =
    BACKSPACE = 27,
    TAB = 28,
    Q = 29, W = 30, E = 31, R = 32, T = 33,
    Y = 34, U = 35, I = 36, O = 37, P = 38,
    LBRACKET = 39, RBRACKET = 40,
    ENTER = 41,
    A = 42, S = 43, D = 44, F = 45, G = 46,
    H = 47, J = 48, K = 49, L = 50,
    SEMICOLON = 51,
    APOSTROPHE = 52,
    BACKSLASH = 53,
    Z = 54, X = 55, C = 56, V = 57, B = 58,
    N = 59, M = 60,
    COMMA = 61, PERIOD = 62, SLASH = 63,
    SPACE = 64,
    INSERT = 65, DELETE = 66,
    HOME = 67, END = 68,
    PAGEUP = 69, PAGEDOWN = 70,
    ARROW_UP = 71, ARROW_DOWN = 72,
    ARROW_LEFT = 73, ARROW_RIGHT = 74,
    CAPSLOCK = 75,
    LSHIFT = 76, RSHIFT = 77,
    LCTRL = 78, RCTRL = 79,
    LALT = 80, RALT = 81,
    LSUPER = 82, RSUPER = 83,
};

#ifdef __linux__

inline const std::unordered_map<uint8_t, int> &genericToLinux() {
    static const std::unordered_map<uint8_t, int> map = {
        {static_cast<uint8_t>(GenericKey::ESC),       KEY_ESC},
        {static_cast<uint8_t>(GenericKey::F1),        KEY_F1},
        {static_cast<uint8_t>(GenericKey::F2),        KEY_F2},
        {static_cast<uint8_t>(GenericKey::F3),        KEY_F3},
        {static_cast<uint8_t>(GenericKey::F4),        KEY_F4},
        {static_cast<uint8_t>(GenericKey::F5),        KEY_F5},
        {static_cast<uint8_t>(GenericKey::F6),        KEY_F6},
        {static_cast<uint8_t>(GenericKey::F7),        KEY_F7},
        {static_cast<uint8_t>(GenericKey::F8),        KEY_F8},
        {static_cast<uint8_t>(GenericKey::F9),        KEY_F9},
        {static_cast<uint8_t>(GenericKey::F10),       KEY_F10},
        {static_cast<uint8_t>(GenericKey::F11),       KEY_F11},
        {static_cast<uint8_t>(GenericKey::F12),       KEY_F12},
        {static_cast<uint8_t>(GenericKey::GRAVE),     KEY_GRAVE},
        {static_cast<uint8_t>(GenericKey::NUM_1),     KEY_1},
        {static_cast<uint8_t>(GenericKey::NUM_2),     KEY_2},
        {static_cast<uint8_t>(GenericKey::NUM_3),     KEY_3},
        {static_cast<uint8_t>(GenericKey::NUM_4),     KEY_4},
        {static_cast<uint8_t>(GenericKey::NUM_5),     KEY_5},
        {static_cast<uint8_t>(GenericKey::NUM_6),     KEY_6},
        {static_cast<uint8_t>(GenericKey::NUM_7),     KEY_7},
        {static_cast<uint8_t>(GenericKey::NUM_8),     KEY_8},
        {static_cast<uint8_t>(GenericKey::NUM_9),     KEY_9},
        {static_cast<uint8_t>(GenericKey::NUM_0),     KEY_0},
        {static_cast<uint8_t>(GenericKey::MINUS),     KEY_MINUS},
        {static_cast<uint8_t>(GenericKey::EQUALS),   KEY_EQUAL},
        {static_cast<uint8_t>(GenericKey::BACKSPACE), KEY_BACKSPACE},
        {static_cast<uint8_t>(GenericKey::TAB),       KEY_TAB},
        {static_cast<uint8_t>(GenericKey::Q),         KEY_Q},
        {static_cast<uint8_t>(GenericKey::W),         KEY_W},
        {static_cast<uint8_t>(GenericKey::E),         KEY_E},
        {static_cast<uint8_t>(GenericKey::R),         KEY_R},
        {static_cast<uint8_t>(GenericKey::T),         KEY_T},
        {static_cast<uint8_t>(GenericKey::Y),         KEY_Y},
        {static_cast<uint8_t>(GenericKey::U),         KEY_U},
        {static_cast<uint8_t>(GenericKey::I),         KEY_I},
        {static_cast<uint8_t>(GenericKey::O),         KEY_O},
        {static_cast<uint8_t>(GenericKey::P),         KEY_P},
        {static_cast<uint8_t>(GenericKey::LBRACKET),  KEY_LEFTBRACE},
        {static_cast<uint8_t>(GenericKey::RBRACKET),  KEY_RIGHTBRACE},
        {static_cast<uint8_t>(GenericKey::ENTER),     KEY_ENTER},
        {static_cast<uint8_t>(GenericKey::A),         KEY_A},
        {static_cast<uint8_t>(GenericKey::S),         KEY_S},
        {static_cast<uint8_t>(GenericKey::D),         KEY_D},
        {static_cast<uint8_t>(GenericKey::F),         KEY_F},
        {static_cast<uint8_t>(GenericKey::G),         KEY_G},
        {static_cast<uint8_t>(GenericKey::H),         KEY_H},
        {static_cast<uint8_t>(GenericKey::J),         KEY_J},
        {static_cast<uint8_t>(GenericKey::K),         KEY_K},
        {static_cast<uint8_t>(GenericKey::L),         KEY_L},
        {static_cast<uint8_t>(GenericKey::SEMICOLON), KEY_SEMICOLON},
        {static_cast<uint8_t>(GenericKey::APOSTROPHE), KEY_APOSTROPHE},
        {static_cast<uint8_t>(GenericKey::BACKSLASH), KEY_BACKSLASH},
        {static_cast<uint8_t>(GenericKey::Z),         KEY_Z},
        {static_cast<uint8_t>(GenericKey::X),         KEY_X},
        {static_cast<uint8_t>(GenericKey::C),         KEY_C},
        {static_cast<uint8_t>(GenericKey::V),         KEY_V},
        {static_cast<uint8_t>(GenericKey::B),         KEY_B},
        {static_cast<uint8_t>(GenericKey::N),         KEY_N},
        {static_cast<uint8_t>(GenericKey::M),         KEY_M},
        {static_cast<uint8_t>(GenericKey::COMMA),     KEY_COMMA},
        {static_cast<uint8_t>(GenericKey::PERIOD),    KEY_DOT},
        {static_cast<uint8_t>(GenericKey::SLASH),     KEY_SLASH},
        {static_cast<uint8_t>(GenericKey::SPACE),     KEY_SPACE},
        {static_cast<uint8_t>(GenericKey::INSERT),    KEY_INSERT},
        {static_cast<uint8_t>(GenericKey::DELETE),    KEY_DELETE},
        {static_cast<uint8_t>(GenericKey::HOME),      KEY_HOME},
        {static_cast<uint8_t>(GenericKey::END),       KEY_END},
        {static_cast<uint8_t>(GenericKey::PAGEUP),    KEY_PAGEUP},
        {static_cast<uint8_t>(GenericKey::PAGEDOWN),  KEY_PAGEDOWN},
        {static_cast<uint8_t>(GenericKey::ARROW_UP),   KEY_UP},
        {static_cast<uint8_t>(GenericKey::ARROW_DOWN), KEY_DOWN},
        {static_cast<uint8_t>(GenericKey::ARROW_LEFT), KEY_LEFT},
        {static_cast<uint8_t>(GenericKey::ARROW_RIGHT),KEY_RIGHT},
        {static_cast<uint8_t>(GenericKey::CAPSLOCK),  KEY_CAPSLOCK},
        {static_cast<uint8_t>(GenericKey::LSHIFT),     KEY_LEFTSHIFT},
        {static_cast<uint8_t>(GenericKey::RSHIFT),     KEY_RIGHTSHIFT},
        {static_cast<uint8_t>(GenericKey::LCTRL),      KEY_LEFTCTRL},
        {static_cast<uint8_t>(GenericKey::RCTRL),      KEY_RIGHTCTRL},
        {static_cast<uint8_t>(GenericKey::LALT),       KEY_LEFTALT},
        {static_cast<uint8_t>(GenericKey::RALT),       KEY_RIGHTALT},
        {static_cast<uint8_t>(GenericKey::LSUPER),     KEY_LEFTMETA},
        {static_cast<uint8_t>(GenericKey::RSUPER),     KEY_RIGHTMETA},
    };
    return map;
}

#elif defined(_WIN32)

inline const std::unordered_map<uint8_t, int> &genericToWindows() {
    static const std::unordered_map<uint8_t, int> map = {
        {static_cast<uint8_t>(GenericKey::ESC),       VK_ESCAPE},
        {static_cast<uint8_t>(GenericKey::F1),        VK_F1},
        {static_cast<uint8_t>(GenericKey::F2),        VK_F2},
        {static_cast<uint8_t>(GenericKey::F3),        VK_F3},
        {static_cast<uint8_t>(GenericKey::F4),        VK_F4},
        {static_cast<uint8_t>(GenericKey::F5),        VK_F5},
        {static_cast<uint8_t>(GenericKey::F6),        VK_F6},
        {static_cast<uint8_t>(GenericKey::F7),        VK_F7},
        {static_cast<uint8_t>(GenericKey::F8),        VK_F8},
        {static_cast<uint8_t>(GenericKey::F9),        VK_F9},
        {static_cast<uint8_t>(GenericKey::F10),       VK_F10},
        {static_cast<uint8_t>(GenericKey::F11),       VK_F11},
        {static_cast<uint8_t>(GenericKey::F12),       VK_F12},
        {static_cast<uint8_t>(GenericKey::GRAVE),     0xC0},
        {static_cast<uint8_t>(GenericKey::NUM_1),     '1'},
        {static_cast<uint8_t>(GenericKey::NUM_2),     '2'},
        {static_cast<uint8_t>(GenericKey::NUM_3),     '3'},
        {static_cast<uint8_t>(GenericKey::NUM_4),     '4'},
        {static_cast<uint8_t>(GenericKey::NUM_5),     '5'},
        {static_cast<uint8_t>(GenericKey::NUM_6),     '6'},
        {static_cast<uint8_t>(GenericKey::NUM_7),     '7'},
        {static_cast<uint8_t>(GenericKey::NUM_8),     '8'},
        {static_cast<uint8_t>(GenericKey::NUM_9),     '9'},
        {static_cast<uint8_t>(GenericKey::NUM_0),     '0'},
        {static_cast<uint8_t>(GenericKey::MINUS),     VK_OEM_MINUS},
        {static_cast<uint8_t>(GenericKey::EQUALS),    VK_OEM_PLUS},
        {static_cast<uint8_t>(GenericKey::BACKSPACE), VK_BACK},
        {static_cast<uint8_t>(GenericKey::TAB),       VK_TAB},
        {static_cast<uint8_t>(GenericKey::Q),         'Q'},
        {static_cast<uint8_t>(GenericKey::W),         'W'},
        {static_cast<uint8_t>(GenericKey::E),         'E'},
        {static_cast<uint8_t>(GenericKey::R),         'R'},
        {static_cast<uint8_t>(GenericKey::T),         'T'},
        {static_cast<uint8_t>(GenericKey::Y),         'Y'},
        {static_cast<uint8_t>(GenericKey::U),         'U'},
        {static_cast<uint8_t>(GenericKey::I),         'I'},
        {static_cast<uint8_t>(GenericKey::O),         'O'},
        {static_cast<uint8_t>(GenericKey::P),         'P'},
        {static_cast<uint8_t>(GenericKey::LBRACKET),  VK_OEM_4},
        {static_cast<uint8_t>(GenericKey::RBRACKET),  VK_OEM_6},
        {static_cast<uint8_t>(GenericKey::ENTER),     VK_RETURN},
        {static_cast<uint8_t>(GenericKey::A),         'A'},
        {static_cast<uint8_t>(GenericKey::S),         'S'},
        {static_cast<uint8_t>(GenericKey::D),         'D'},
        {static_cast<uint8_t>(GenericKey::F),         'F'},
        {static_cast<uint8_t>(GenericKey::G),         'G'},
        {static_cast<uint8_t>(GenericKey::H),         'H'},
        {static_cast<uint8_t>(GenericKey::J),         'J'},
        {static_cast<uint8_t>(GenericKey::K),         'K'},
        {static_cast<uint8_t>(GenericKey::L),         'L'},
        {static_cast<uint8_t>(GenericKey::SEMICOLON), VK_OEM_1},
        {static_cast<uint8_t>(GenericKey::APOSTROPHE), VK_OEM_7},
        {static_cast<uint8_t>(GenericKey::BACKSLASH), VK_OEM_5},
        {static_cast<uint8_t>(GenericKey::Z),         'Z'},
        {static_cast<uint8_t>(GenericKey::X),         'X'},
        {static_cast<uint8_t>(GenericKey::C),         'C'},
        {static_cast<uint8_t>(GenericKey::V),         'V'},
        {static_cast<uint8_t>(GenericKey::B),         'B'},
        {static_cast<uint8_t>(GenericKey::N),         'N'},
        {static_cast<uint8_t>(GenericKey::M),         'M'},
        {static_cast<uint8_t>(GenericKey::COMMA),     VK_OEM_COMMA},
        {static_cast<uint8_t>(GenericKey::PERIOD),    VK_OEM_PERIOD},
        {static_cast<uint8_t>(GenericKey::SLASH),     VK_OEM_2},
        {static_cast<uint8_t>(GenericKey::SPACE),     VK_SPACE},
        {static_cast<uint8_t>(GenericKey::INSERT),    VK_INSERT},
        {static_cast<uint8_t>(GenericKey::DELETE),    VK_DELETE},
        {static_cast<uint8_t>(GenericKey::HOME),      VK_HOME},
        {static_cast<uint8_t>(GenericKey::END),       VK_END},
        {static_cast<uint8_t>(GenericKey::PAGEUP),    VK_PRIOR},
        {static_cast<uint8_t>(GenericKey::PAGEDOWN),  VK_NEXT},
        {static_cast<uint8_t>(GenericKey::ARROW_UP),   VK_UP},
        {static_cast<uint8_t>(GenericKey::ARROW_DOWN), VK_DOWN},
        {static_cast<uint8_t>(GenericKey::ARROW_LEFT), VK_LEFT},
        {static_cast<uint8_t>(GenericKey::ARROW_RIGHT),VK_RIGHT},
        {static_cast<uint8_t>(GenericKey::CAPSLOCK),  VK_CAPITAL},
        {static_cast<uint8_t>(GenericKey::LSHIFT),     VK_LSHIFT},
        {static_cast<uint8_t>(GenericKey::RSHIFT),     VK_RSHIFT},
        {static_cast<uint8_t>(GenericKey::LCTRL),      VK_LCONTROL},
        {static_cast<uint8_t>(GenericKey::RCTRL),      VK_RCONTROL},
        {static_cast<uint8_t>(GenericKey::LALT),       VK_LMENU},
        {static_cast<uint8_t>(GenericKey::RALT),       VK_RMENU},
        {static_cast<uint8_t>(GenericKey::LSUPER),     VK_LWIN},
        {static_cast<uint8_t>(GenericKey::RSUPER),     VK_RWIN},
    };
    return map;
}

#endif

} // namespace KeyMapping